name: linux
on:
  push:
    tags:
      - '*'
    branches:
      - dev
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - { base_image: i386/alpine, platform: linux/386, suffix: linux-32bit }
          - { base_image: alpine, platform: linux/amd64, suffix: linux-64bit }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker buildx build --platform ${{ matrix.platform }} --load -t cutechess - << EOF
          FROM ${{ matrix.base_image }}
          WORKDIR /app
          RUN apk update && apk add sudo perl python3 git zip make cmake ninja g++ linux-headers mesa-dev
          CMD ["sh", "make_cute_posix.sh"]
          EOF
      - name: Build cutechess
        run: docker run --rm --platform ${{ matrix.platform }} -v ${{ github.workspace }}:/app cutechess
      - name: Test cutechess-cli
        run: |
          unzip cutechess-cli.zip
          ./cutechess-cli --version
          file cutechess-cli
      - name: Rename archive
        run: mv cutechess-cli.zip cutechess-cli-${{ matrix.suffix }}.zip
      - name: VirusTotal Monitor Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: cutechess-cli-${{ matrix.suffix }}.zip
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: cutechess-cli-${{ matrix.suffix }}.zip
          path: cutechess-cli-${{ matrix.suffix }}.zip
      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: cutechess-cli-${{ matrix.suffix }}.zip
