name: windows
on:
  push:
    tags:
      - '*'
    branches:
      - dev
defaults:
  run:
    shell: msys2 {0}
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686, suffix: windows-32bit }
          - { sys: mingw64, env: x86_64, suffix: windows-64bit }
    steps:
      - name: Setup msys and install required packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.sys }}
          install: >-
            git
            make
            zip
            unzip
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-gcc
            mingw-w64-${{ matrix.env }}-qt5-static
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build cutechess
        run: sh make_cute_windows.sh
      - name: Test cutechess-cli
        run: |
          unzip cutechess-cli.zip
          ./cutechess-cli.exe --version
          file cutechess-cli.exe
      - name: Rename archive
        run: mv cutechess-cli.zip cutechess-cli-${{ matrix.suffix }}.zip
      - name: VirusTotal Monitor Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: cutechess-cli-${{ matrix.suffix }}.zip
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: cutechess-cli-${{ matrix.suffix }}.zip
          path: cutechess-cli-${{ matrix.suffix }}.zip
      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: cutechess-cli-${{ matrix.suffix }}.zip
